server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mario1980miranda/ead-config-server-repo
          default-label: main
          username: mario1980miranda
          password: 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
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
